CREATE TABLE [dbo].[INTELLISENSE_TAG_CONN] (
  [ID] numeric(15, 0) IDENTITY(1, 1) NOT NULL,
  [INTELLISENSE_ID] numeric(15, 0) NOT NULL,
  [TAG_ID] numeric(15, 0) NOT NULL,
  CONSTRAINT [PK_INTELLISENSETAGCONN] PRIMARY KEY NONCLUSTERED ([ID]),
  CONSTRAINT [FK_ITC_INTELLISENSEID] FOREIGN KEY ([INTELLISENSE_ID]) 
	  REFERENCES [dbo].[INTELLISENSE] ([ID]) 
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION,
  CONSTRAINT [FK_ITC_TAGID] FOREIGN KEY ([TAG_ID]) 
	  REFERENCES [dbo].[TAG] ([ID]) 
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION
)
ON [PRIMARY]
GO